name: 'YAML Region Tag Generator'
description: 'Adds YAML region tags'
author: 'askmeegs'
branding:
  icon: code
  color: yellow
inputs:
  github_token:
    description: 'github id_rsa token'
    required: true
    default: ''
  repository:
    description: 'repository name'
    default: ''
    required: true
  branch:
    description: 'destination branch'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.repository }}
    - ${{ inputs.branch }}